# -*- coding: utf-8 -*-
"""SSMIF2.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7fSJAPV-m3nIL2NA1nt9EkaZP3eTexL

# Mounting Gdrive
"""

#importing all of the dependencies
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import joblib


path = "ML_Question_Data_Clean.csv"
#Setting up the CSV training data
data = pd.read_csv(path)
data.head()

#Splitting the data into training and validation sets (needed to show accuracy)
x_train, x_test, y_train, y_test = train_test_split(data[['feature1', 'feature2', 'feature3','feature4', 'feature5', 'feature6']], data['Target'], test_size = .2)


#How I trained the Model:
''' 
f = RandomForestRegressor(n_estimators=1000, max_depth=None, n_jobs=-1)
rf_model = rf.fit(x_train, y_train)
'''



def predict():
    """I loaded and showed the mean squared error of my exported Random Forest Regression Model
    The section above shows how I trained my model."""
    rf_model = joblib.load("Burak's_Model_Final.pkl") #Loading the model and trained
    y_pred_r = rf_model.predict(x_test)
    MSE = mean_squared_error(y_test, y_pred_r)
    return MSE

